2024-12-29 19:32:17.044431: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA
/home/lei/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:523: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/lei/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:524: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/lei/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/lei/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/lei/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/lei/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:532: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])

##### Information #####
# dataset :  FFHQ
# dataset number :  1
# gpu :  3
# batch_size in train phase :  OrderedDict([(4, 128), (8, 128), (16, 64), (32, 32), (64, 16), (128, 8), (256, 4), (512, 4), (1024, 4)])
# batch_size in test phase :  1
# start resolution :  8
# target resolution :  8
# iteration per resolution :  10000
# progressive training :  True
# spectral normalization :  False

Traceback (most recent call last):
  File "main.py", line 102, in <module>
    main()
  File "main.py", line 74, in main
    gan.build_model()
  File "/home/lei/compatibility_analysis/tensorflow/1.13/StyleGAN-Tensorflow/StyleGAN.py", line 326, in build_model
    apply(map_and_batch(image_class.image_processing, batch_size, num_parallel_batches=16, drop_remainder=True)). \
  File "/home/lei/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 1128, in apply
    dataset = transformation_func(self)
  File "/home/lei/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/contrib/data/python/ops/batching.py", line 793, in _apply_fn
    num_parallel_calls, drop_remainder)
  File "/home/lei/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/contrib/data/python/ops/batching.py", line 705, in __init__
    super(_MapAndBatchDataset, self).__init__(input_dataset, map_func)
  File "/home/lei/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 2216, in __init__
    map_func, "Dataset.map()", input_dataset)
  File "/home/lei/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 1473, in __init__
    self._function.add_to_graph(ops.get_default_graph())
  File "/home/lei/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/framework/function.py", line 479, in add_to_graph
    self._create_definition_if_needed()
  File "/home/lei/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/framework/function.py", line 335, in _create_definition_if_needed
    self._create_definition_if_needed_impl()
  File "/home/lei/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/framework/function.py", line 344, in _create_definition_if_needed_impl
    self._capture_by_value, self._caller_device)
  File "/home/lei/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/framework/function.py", line 865, in func_graph_from_py_func
    outputs = func(*func_graph.inputs)
  File "/home/lei/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 1411, in tf_data_structured_function_wrapper
    ret = func(*nested_args)
  File "/home/lei/compatibility_analysis/tensorflow/1.13/StyleGAN-Tensorflow/utils.py", line 19, in image_processing
    img = preprocess_fit_train_image(img, self.img_size)
  File "/home/lei/compatibility_analysis/tensorflow/1.13/StyleGAN-Tensorflow/utils.py", line 50, in preprocess_fit_train_image
    images = tf.image.resize(images, size=[res, res], method=tf.image.ResizeMethod.BILINEAR)
AttributeError: module 'tensorflow.image' has no attribute 'resize'
