
                        **Debug Mission** 
                        Resolve runtime crash caused by code-level incompatibilities in dependency chain.

                        **Input Context**
                        - Current environment: absl-py==0.15.0
astunparse==1.6.3
cachetools==4.2.4
certifi==2021.5.30
charset-normalizer==2.0.12
cycler==0.11.0
dataclasses==0.8
editdistance==0.5.2
flatbuffers==1.12
gast==0.4.0
google-auth==1.35.0
google-auth-oauthlib==0.4.4
google-pasta==0.2.0
grpcio==1.37.0
h5py==3.1.0
idna==2.10
importlib-metadata==4.8.3
Keras-Preprocessing==1.1.2
kiwisolver==1.3.1
lmdb==1.0.0
Markdown==3.3.7
matplotlib==3.2.1
numpy==1.19.5
oauthlib==3.1.0
opencv-python==4.4.0.46
opt-einsum==3.3.0
path==15.0.0
protobuf==3.17.3
pyasn1==0.4.8
pyasn1-modules==0.2.8
pyparsing==2.4.7
python-dateutil==2.8.1
requests==2.25.1
requests-oauthlib==1.3.0
rsa==4.7
six==1.15.0
tensorboard==2.6.0
tensorboard-data-server==0.6.1
tensorboard-plugin-wit==1.8.0
tensorflow==2.6.0
tensorflow-estimator==2.6.0
termcolor==1.1.0
typing-extensions==3.7.4.3
urllib3==1.26.6
Werkzeug==2.0.1
wrapt==1.12.1
zipp==3.6.0

                        - Python version: 3.6
                        - Crash traceback: Traceback (most recent call last):
  File "main.py", line 202, in <module>
    main()
  File "main.py", line 197, in main
    model = Model(char_list_from_file(), decoder_type, must_restore=True, dump=args.dump)
  File "/home/lei/compatibility_analysis/tensorflow/2.4/SimpleHTR/src/model.py", line 43, in __init__
    self.setup_cnn()
  File "/home/lei/compatibility_analysis/tensorflow/2.4/SimpleHTR/src/model.py", line 73, in setup_cnn
    conv_norm = tf.compat.v1.layers.batch_normalization(conv, training=self.is_train)
  File "/home/lei/anaconda3/envs/py36-1/lib/python3.6/site-packages/tensorflow/python/util/lazy_loader.py", line 62, in __getattr__
    module = self._load()
  File "/home/lei/anaconda3/envs/py36-1/lib/python3.6/site-packages/tensorflow/python/util/lazy_loader.py", line 45, in _load
    module = importlib.import_module(self.__name__)
  File "/home/lei/anaconda3/envs/py36-1/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/lei/anaconda3/envs/py36-1/lib/python3.6/site-packages/keras/__init__.py", line 20, in <module>
    from keras import distribute
  File "/home/lei/anaconda3/envs/py36-1/lib/python3.6/site-packages/keras/distribute/__init__.py", line 18, in <module>
    from keras.distribute import sidecar_evaluator
  File "/home/lei/anaconda3/envs/py36-1/lib/python3.6/site-packages/keras/distribute/sidecar_evaluator.py", line 22, in <module>
    from keras.optimizers.optimizer_experimental import (
  File "/home/lei/anaconda3/envs/py36-1/lib/python3.6/site-packages/keras/optimizers/__init__.py", line 26, in <module>
    from keras.optimizers.legacy import adadelta as adadelta_legacy
  File "/home/lei/anaconda3/envs/py36-1/lib/python3.6/site-packages/keras/optimizers/legacy/adadelta.py", line 17, in <module>
    from keras.optimizers.optimizer_v2 import adadelta
  File "/home/lei/anaconda3/envs/py36-1/lib/python3.6/site-packages/keras/optimizers/optimizer_v2/adadelta.py", line 21, in <module>
    from keras.optimizers.optimizer_v2 import optimizer_v2
  File "/home/lei/anaconda3/envs/py36-1/lib/python3.6/site-packages/keras/optimizers/optimizer_v2/optimizer_v2.py", line 26, in <module>
    from keras import initializers
  File "/home/lei/anaconda3/envs/py36-1/lib/python3.6/site-packages/keras/initializers/__init__.py", line 22, in <module>
    from keras.initializers import initializers_v2
  File "/home/lei/anaconda3/envs/py36-1/lib/python3.6/site-packages/keras/initializers/initializers_v2.py", line 23, in <module>
    from keras.dtensor import utils
  File "/home/lei/anaconda3/envs/py36-1/lib/python3.6/site-packages/keras/dtensor/__init__.py", line 22, in <module>
    from tensorflow.compat.v2.experimental import dtensor as dtensor_api
ImportError: cannot import name 'dtensor'


                        **Analysis Protocol**
                        1. Traceback Pattern Matching：
                        a. Identify error type (ImportError/AttributeError/TypeError)
                        b. Map to possible API changes in tensorflow v2.6.0 or its dependencies
                        2. Compatibility Matrix Check：
                        a. Verify library-to-library API compatibility through version ranges
                        b. Confirm project-to-library interface compatibility
                        3. Breakpoint Isolation：
                        b. Determine if conflict originates from：
                            • Direct API changes in tensorflow
                            • Transitive dependency API shifts

                        **Resolution Rules**
                        - PRIMARY CONSTRAINT: Maintain tensorflow==2.6.0
                        - SECONDARY ADJUSTMENTS: 
                        • Modify dependency versions only when API contracts allow
                        • Prefer backward-compatible minor version changes

                        **Output Mandates**
                        STRICT FORMAT:
                        lib1==x.y.z  
                        lib2==a.b.c
                        ...
                        PROHIBITED:
                        • Any non-version text.
                        • Library additions/removals
                        • Version placeholders
                        MANDATORY:
                        • Preserve original library names and count
                        • Pin EXACT versions
                        • Zero explanations/comments
                        